#!/bin/bash

echo "Do sync"
sync

platform_specific_op_sysfs="/sys/bus/i2c/devices/1-0065/reset_mac_before_reboot"
do_cpld_cold_reset=true
if [ -f "$platform_specific_op_sysfs" ]; then
    if [ 1 == $(<$platform_specific_op_sysfs) ]; then
        do_cpld_cold_reset=false
    fi
fi

echo "Stop pmon.service"
systemctl stop pmon.service

echo "Stop as9726-32d-platform-monitor-fan.service"
systemctl stop as9726-32d-platform-monitor-fan.service

echo "Stop as9726-32d-platform-monitor-psu.service"
systemctl stop as9726-32d-platform-monitor-psu.service

echo "Stop as9726-32d-platform-monitor.service"
systemctl stop as9726-32d-platform-monitor.service

if [ "$do_cpld_cold_reset" = true ]; then
    echo "Cold Reset via CPLD Offset 0x4 Bit 3"
    i2cset -y -f 1 0x65 0x4 0x15
fi
